name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.6.1
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Build application
      run: pnpm run build
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Link Railway Project
      run: railway link --project ea37462e-6e31-4be4-88d0-ba9dbd655be0
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
    - name: Deploy to Railway
      run: railway up --detach
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
